  version: 0.0
  os: linux
  hooks:
    BeforeInstall:
      - location: scripts/before-install.sh
        timeout: 300
        runas: root
    AfterInstall:
      - location: scripts/after-install.sh
        timeout: 300
        runas: root
    ApplicationStart:
      - location: scripts/application-start.sh
        timeout: 300
        runas: root