version: 0.3

phases:
  install:
    commands:
      - echo Installing dependency...
      - yarn install
  pre_build:
    commands:
      - printenv > .env
  build:
    commands:
      - echo Compiling the Node.js code
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
