import './globals.css'
import { Providers } from './providers'
import { ReactNode } from "react";

export const metadata = {
  title: 'Guanhua Ding',
  description: 'Generated by create next app',
}

interface Props {
  children?: ReactNode
  // any props that come into the component
}

export default function Layout({ children }: Props) {
  return (
    <html suppressHydrationWarning>
      <head />
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
