import './globals.css'
import { Providers } from './providers'

export const metadata = {
  title: 'Guanhua Ding',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
    <html suppressHydrationWarning>
      <head />
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
